SET AUTOBATCHSEQU=C:\Users\lixy\Downloads\Acrobat\OCR.sequ
SET AUTOBATCHFINAL=0
SET AUTOBATCHDEST=
SET AUTOBATCHALTPATH=%1
SET AUTOBATCHALTOUTPUTPATH=%2
SET AUTOBATCHNOPROGRESS=no
SET AUTOBATCHFILEEXT=
SET AUTOBATCHNOSUBFOLDERS=no
"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\Acrobat.exe" /n