CREATE TABLE users
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
email VARCHAR(256) NOT NULL,
password VARCHAR(256) NOT NULL,
create_time BIGINT NOT NULL,
CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE INDEX index_email ON users(email);

CREATE TABLE download_record
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
user_id INTEGER,
url VARCHAR(1024) NOT NULL,
create_time BIGINT NOT NULL,
file_id INTEGER,
payment_time BIGINT NOT NULL,
CONSTRAINT pk_dr PRIMARY KEY (id)
);

CREATE TABLE download_file
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
url VARCHAR(1024) NOT NULL,
create_time BIGINT NOT NULL,
name VARCHAR(1024),
encrypt_name VARCHAR(64),
type VARCHAR(64),
total_pages SMALLINT,
CONSTRAINT pk_df PRIMARY KEY (id)
);

CREATE INDEX index1 ON download_file(encrypt_name);